# Generated by Django 5.0.2 on 2024-02-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_id',
        ),
    ]
